---
swap_size: 2G
users:
  - name: "user"
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIErK/LPcV0vULwgZgFpJMc49gO6LN3RQXQtRGHYk3YcM boborg144@gmail.com"

ssh_users:
  - name: "user"
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIErK/LPcV0vULwgZgFpJMc49gO6LN3RQXQtRGHYk3YcM boborg144@gmail.com"

sudoers_users:
  - "user"